# Generated by Django 6.0.2 on 2026-03-23 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('token_amount', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.creator')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('genre', models.CharField(choices=[('JAZZ', 'Jazz'), ('ROCK', 'Rock'), ('POP', 'Pop'), ('HIPHOP', 'Hip Hop'), ('CLASSICAL', 'Classical'), ('EDM', 'EDM'), ('RNB', 'R&B'), ('FOLK', 'Folk'), ('METAL', 'Metal'), ('OTHER', 'Other')], max_length=20)),
                ('vocal_style', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('DUET', 'Duet'), ('INSTRUMENTAL', 'Instrumental'), ('RAP', 'Rap'), ('OTHER', 'Other')], max_length=20)),
                ('occasion', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('WEDDING', 'Wedding'), ('STUDY', 'Study'), ('WORKOUT', 'Workout'), ('PARTY', 'Party'), ('RELAX', 'Relax'), ('OTHER', 'Other')], max_length=20)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared')], default='PRIVATE', max_length=20)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('audio_location', models.CharField(blank=True, max_length=500, null=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.library')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('genre', models.CharField(choices=[('JAZZ', 'Jazz'), ('ROCK', 'Rock'), ('POP', 'Pop'), ('HIPHOP', 'Hip Hop'), ('CLASSICAL', 'Classical'), ('EDM', 'EDM'), ('RNB', 'R&B'), ('FOLK', 'Folk'), ('METAL', 'Metal'), ('OTHER', 'Other')], max_length=50)),
                ('vocal_style', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('DUET', 'Duet'), ('INSTRUMENTAL', 'Instrumental'), ('RAP', 'Rap'), ('OTHER', 'Other')], max_length=50)),
                ('occasion', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('WEDDING', 'Wedding'), ('STUDY', 'Study'), ('WORKOUT', 'Workout'), ('PARTY', 'Party'), ('RELAX', 'Relax'), ('OTHER', 'Other')], max_length=50)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.creator')),
                ('song', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.song')),
            ],
        ),
    ]
