# Generated by Django 6.0.2 on 2026-04-24 17:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('token_amount', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('genre', models.CharField(choices=[('JAZZ', 'Jazz'), ('ROCK', 'Rock'), ('POP', 'Pop'), ('HIPHOP', 'Hip Hop'), ('CLASSICAL', 'Classical'), ('EDM', 'EDM'), ('RNB', 'R&B'), ('FOLK', 'Folk'), ('METAL', 'Metal'), ('OTHER', 'Other')], max_length=20)),
                ('vocal_style', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('DUET', 'Duet'), ('INSTRUMENTAL', 'Instrumental'), ('RAP', 'Rap'), ('OTHER', 'Other')], max_length=20)),
                ('occasion', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('WEDDING', 'Wedding'), ('STUDY', 'Study'), ('WORKOUT', 'Workout'), ('PARTY', 'Party'), ('RELAX', 'Relax'), ('OTHER', 'Other')], max_length=20)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared')], default='PRIVATE', max_length=20)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('audio_location', models.CharField(blank=True, max_length=500, null=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.library')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('genre', models.CharField(choices=[('JAZZ', 'Jazz'), ('ROCK', 'Rock'), ('POP', 'Pop'), ('HIPHOP', 'Hip Hop'), ('CLASSICAL', 'Classical'), ('EDM', 'EDM'), ('RNB', 'R&B'), ('FOLK', 'Folk'), ('METAL', 'Metal'), ('OTHER', 'Other')], max_length=50)),
                ('vocal_style', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('DUET', 'Duet'), ('INSTRUMENTAL', 'Instrumental'), ('RAP', 'Rap'), ('OTHER', 'Other')], max_length=50)),
                ('occasion', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('WEDDING', 'Wedding'), ('STUDY', 'Study'), ('WORKOUT', 'Workout'), ('PARTY', 'Party'), ('RELAX', 'Relax'), ('OTHER', 'Other')], max_length=50)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.song')),
            ],
        ),
        migrations.CreateModel(
            name='OAuthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google')], max_length=50)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
