# Generated by Django 6.0.2 on 2026-04-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('GENERATING', 'Generating'), ('SAVING', 'Saving'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20),
        ),
    ]
