# Generated by Django 6.0.2 on 2026-04-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='last_token_replenish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
